[package]
name = "rust_lldp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = { version = "0.9", features = ["capture-stream"] }
rshark = "0.0.1"
byteorder = "1.4.3"
nom = "7"